# Generated by Django 4.0.2 on 2022-02-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(max_length=200),
        ),
    ]
